name: 'CI'

on: 
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test:
    name: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3

        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
        - name: Install modules
          run: npm install

        - run: npm run lint
          if: ${{ always() }}
        - run: npm run tsc
          if: ${{ always() }}
        - run: npm run build
          if: ${{ always() }}


